FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Taipei

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    autoconf \
    automake \
    libtool \
    pkg-config \
    libgstreamer1.0-dev \
    libgstreamer-plugins-base1.0-dev \
    libgstreamer-plugins-bad1.0-dev \
    gstreamer1.0-plugins-base \
    libva-dev \
    libva-drm2 \
    libdrm-dev \
    libexpat-dev \
    libjsoncpp-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
